name: Run Python Script

on:
  push:
    branches:
      - pythonanywhere2  # This triggers the workflow on pushes to the pythonanywhere2 branch
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies if you have a requirements file

    - name: Run main.py
      run: python main.py  # Adjust the path if necessary
